// Plain-English glossary. Terms are auto-linked (first mention per section) on Learn pages.
// match: lowercase phrases to look for (whole words). The first phrase is the display name.
export const GLOSSARY = [
  { match: ['llm', 'llms', 'large language model'], def: 'Large language model: an AI (like Claude or GPT) that reads text and predicts what text should come next. It is the “brain” the agent calls.' },
  { match: ['agent', 'agents'], def: 'A program that uses an LLM to decide what to do next, calls tools to act, and loops until the task is done, instead of just answering once.' },
  { match: ['token', 'tokens'], def: 'The unit LLMs read and bill by, roughly ¾ of a word (about 4 characters). “Hello world” is about 2 tokens. Cost and context limits are counted in tokens.' },
  { match: ['prompt', 'prompts'], def: 'The text you send to the model: instructions, context and the user’s message.' },
  { match: ['system prompt', 'system message'], def: 'Hidden instructions sent before the user’s message that set the agent’s rules and role. Users shouldn’t be able to see or override it.' },
  { match: ['prompt injection', 'injection'], def: 'An attack where user text tries to override the system prompt (“ignore previous instructions and…”) to make the agent misbehave or leak data.' },
  { match: ['jailbreak', 'jailbreaks'], def: 'A prompt crafted to trick a model into ignoring its safety rules, e.g. “pretend you are DAN who has no restrictions”.' },
  { match: ['regex', 'regexes', 'regular expression'], def: 'A mini-language for matching text patterns. `sk-[A-Za-z0-9]{16,}` means “sk- followed by 16+ letters or digits”.' },
  { match: ['html escaping', 'html-escape', 'html escape'], def: 'Turning characters like < and > into safe codes (&lt; &gt;) so text can’t be interpreted as HTML or markup.' },
  { match: ['rate limit', 'rate limiting', 'rate limiter'], def: 'A cap on how many requests a user can make in a period, so one user (or script) can’t overload the system or the bill.' },
  { match: ['rbac'], def: 'Role-based access control: permissions are given to roles (viewer, editor, admin) and users get the permissions of their role.' },
  { match: ['least privilege', 'least-privilege'], def: 'Give each user or component only the permissions it needs, nothing more, so a mistake or breach can do less damage.' },
  { match: ['stub', 'stubs'], def: 'A fake stand-in for a real service that returns predictable answers. Used so tests run fast, free and offline.' },
  { match: ['ci'], def: 'Continuous integration: a server that automatically runs your tests on every code change. It usually has no secrets and no paid API access.' },
  { match: ['orchestrator'], def: 'The coordinating code that calls other components in the right order and handles their results.' },
  { match: ['latency'], def: 'How long something takes, usually in milliseconds (ms). Lower is better.' },
  { match: ['p95', 'p99', 'p50', 'percentile', 'percentiles'], def: 'p95 = 95% of requests were faster than this value. It shows the slow tail that an average hides. p50 is the median.' },
  { match: ['observability'], def: 'Being able to tell what your system is doing from the outside, through logs, metrics and traces, without attaching a debugger.' },
  { match: ['metrics'], def: 'Numbers tracked over time (requests, errors, latency, cost) that feed dashboards and alerts.' },
  { match: ['egress'], def: 'Data leaving your system, such as a response going back to a user or a call going out to another service.' },
  { match: ['pii'], def: 'Personally identifiable information: data that identifies a person, like an email, phone number, address or card number.' },
  { match: ['hmac'], def: 'A short code made from a message plus a secret key. Anyone with the key can check that the message wasn’t changed; without the key you can’t forge it.' },
  { match: ['hash', 'sha-256', 'sha256'], def: 'A function that turns any data into a fixed-size fingerprint. Change one bit of input and the fingerprint changes completely.' },
  { match: ['ttl'], def: 'Time to live: how long a cached item stays valid before it expires.' },
  { match: ['lru'], def: 'Least recently used: when a cache is full, remove the item that hasn’t been used for the longest time.' },
  { match: ['cache', 'caching'], def: 'A store of recent answers so repeat requests can be served without redoing the expensive work.' },
  { match: ['redis'], def: 'A very fast in-memory database often used for caches, sessions and counters shared between servers.' },
  { match: ['context window'], def: 'The maximum amount of text (in tokens) a model can read in one request: prompt, history and answer combined.' },
  { match: ['fastapi'], def: 'A popular Python framework for building web APIs. The reference projects use it for their endpoints and dashboards.' },
  { match: ['docker', 'container', 'containers'], def: 'A container packages an app with everything it needs so it runs the same anywhere. Docker is the common tool for building and running them.' },
  { match: ['kubernetes'], def: 'A system that runs and manages containers across many machines: restarting failures, scaling copies and rolling out updates.' },
  { match: ['pod', 'pods'], def: 'The smallest unit Kubernetes runs: one or more containers scheduled together on a machine.' },
  { match: ['replica', 'replicas'], def: 'A copy of the same service (or database). Several replicas share traffic and keep things running if one fails.' },
  { match: ['uvicorn', 'worker'], def: 'Uvicorn is the server process that runs a FastAPI app. Each worker is a separate process with its own memory.' },
  { match: ['schema', 'schemas'], def: 'A precise description of what valid data looks like: which fields exist, their types and allowed values.' },
  { match: ['pydantic'], def: 'A Python library that validates data against a schema you define as a class, raising clear errors when data doesn’t fit.' },
  { match: ['json'], def: 'A text format for structured data: {"name": "Ada", "tags": ["x", "y"]}. Most APIs and LLM structured outputs use it.' },
  { match: ['jsonl'], def: 'JSON Lines: one JSON object per line. Common for datasets and logs because it can be streamed line by line.' },
  { match: ['async', 'asyncio', 'coroutine', 'coroutines'], def: 'Async code can pause while waiting (for a network reply, say) and let other work run meanwhile. asyncio is Python’s built-in async library.' },
  { match: ['semaphore'], def: 'A counter that lets at most N tasks proceed at once; the rest wait. Used to cap concurrency.' },
  { match: ['thread', 'threads', 'thread pool'], def: 'A thread is a separate line of execution inside one program, used to do several things at once.' },
  { match: ['sandbox', 'sandboxed'], def: 'A restricted environment where untrusted code runs with limited abilities, so it can’t harm the rest of the system.' },
  { match: ['subprocess', 'child process'], def: 'A separate program started by your program. If it crashes or hangs, it can be killed without taking your program down.' },
  { match: ['ast'], def: 'Abstract syntax tree: code parsed into a tree of parts (numbers, operators, calls) that can be inspected safely without running it.' },
  { match: ['eval()', 'eval'], def: 'A Python function that runs a string as code. Dangerous with untrusted input, because the string can do anything Python can.' },
  { match: ['react'], def: 'Reason + Act: an agent pattern that alternates a thought, a tool action and an observation until it reaches a final answer.' },
  { match: ['few-shot', 'few shot'], def: 'Including a few solved examples in the prompt so the model copies their format and behaviour.' },
  { match: ['chain-of-thought', 'chain of thought'], def: 'Prompting a model to reason step by step before answering, which often improves accuracy on multi-step problems.' },
  { match: ['embedding', 'embeddings'], def: 'A list of numbers representing a piece of text, so that texts with similar meaning have similar numbers.' },
  { match: ['tf-idf'], def: 'Term frequency × inverse document frequency: weights words that are common in one document but rare overall, as a simple way to vectorize text.' },
  { match: ['cosine similarity', 'cosine'], def: 'Measures how similar two vectors are by the angle between them: 1.0 = same direction, 0.0 = nothing in common.' },
  { match: ['vector store', 'vector database', 'vector databases'], def: 'A database that stores embeddings and quickly finds the ones closest to a query.' },
  { match: ['rag'], def: 'Retrieval-augmented generation: search your documents first, put the best matches into the prompt, then let the model answer from them.' },
  { match: ['fine-tuning', 'fine-tune', 'sft'], def: 'Further training a model on your own examples so it learns a style or domain. SFT (supervised fine-tuning) uses question/ideal-answer pairs.' },
  { match: ['golden set', 'golden cases', 'golden suite', 'eval suite'], def: 'A fixed set of test questions with known good answers, used to score every version of a prompt or model the same way.' },
  { match: ['token-f1', 'f1'], def: 'A score from 0 to 1 combining precision (how much of the answer is correct) and recall (how much of the expected answer is present).' },
  { match: ['llm-as-judge', 'judge'], def: 'Using a (usually stronger) model to grade another model’s answers when exact string matching is too strict.' },
  { match: ['a/b'], def: 'Comparing two versions on the same inputs to see which performs better.' },
  { match: ['knowledge graph', 'graph'], def: 'Data stored as things (nodes) and relationships (edges), e.g. alice → used → web_search, so connection questions are answered exactly.' },
  { match: ['neo4j', 'cypher'], def: 'Neo4j is a popular graph database; Cypher is its query language.' },
  { match: ['hpa'], def: 'Horizontal Pod Autoscaler: Kubernetes’ built-in way to add or remove copies of an app based on CPU or memory.' },
  { match: ['keda'], def: 'Kubernetes Event-Driven Autoscaling: scales apps on external signals like queue length, and can scale all the way to zero.' },
  { match: ['scale-to-zero', 'scale to zero'], def: 'Running zero copies when there’s no demand, so idle time costs nothing. The trade-off is a startup delay for the first request.' },
  { match: ['cold start', 'cold starts'], def: 'The delay while a stopped service starts up to handle its first request.' },
  { match: ['configmap', 'configmaps'], def: 'A Kubernetes object holding non-secret settings (like log level) that apps read at startup.' },
  { match: ['readiness', 'liveness'], def: 'Kubernetes health checks. Readiness: “can this copy receive traffic yet?”. Liveness: “is it stuck and needs a restart?”.' },
  { match: ['rolling update', 'rollout'], def: 'Updating an app by replacing copies a few at a time, so some copies are always serving users.' },
  { match: ['soc 2'], def: 'A security audit standard for service companies, covering access control, change management, monitoring and logging, with evidence.' },
  { match: ['hipaa'], def: 'A US law protecting health information. It requires access controls, audit logs, integrity protection and automatic logoff, among other things.' },
  { match: ['phi'], def: 'Protected health information: health data tied to a person, like medical record numbers, diagnoses or birth dates.' },
  { match: ['baa', 'baas'], def: 'Business associate agreement: a HIPAA contract required before sharing PHI with a vendor (including an AI provider).' },
  { match: ['kms'], def: 'Key management service: a cloud service that stores encryption keys and controls who may use them.' },
  { match: ['worm', 'object lock'], def: 'Write once, read many: storage where data can be written but not changed or deleted until a retention period ends.' },
  { match: ['rto'], def: 'Recovery time objective: the maximum acceptable time from an outage until users are served again.' },
  { match: ['rpo'], def: 'Recovery point objective: the maximum acceptable amount of recent data you can lose in a disaster, measured in time.' },
  { match: ['failover'], def: 'Automatically switching traffic from a failed system to a standby copy.' },
  { match: ['route 53'], def: 'Amazon’s DNS service. It can health-check endpoints and redirect traffic to a backup region when the primary fails.' },
  { match: ['replica lag'], def: 'How far behind a database copy is compared with the primary. If the primary dies, that much recent data may be lost.' },
  { match: ['idempotent'], def: 'Safe to repeat: doing it twice has the same effect as doing it once (e.g. “set balance to 10” vs “add 10”).' },
  { match: ['fail closed', 'fails closed'], def: 'When something goes wrong or is uncertain, deny by default rather than allow.' },
  { match: ['fail open', 'fails open'], def: 'When a dependency fails, keep serving in a degraded mode rather than refusing everyone. Right for availability, wrong for security checks.' },
  { match: ['blast radius'], def: 'How much damage a single failure or breach can cause. Isolation and least privilege shrink it.' },
  { match: ['slo', 'slos'], def: 'Service level objective: a target like “99.9% of requests succeed in under 500 ms”.' },
  { match: ['finops'], def: 'The practice of tracking and optimizing cloud spend as an engineering concern.' },
  { match: ['allowlist', 'allow-list', 'deny-list', 'denylist'], def: 'An allowlist permits only listed items (everything else is blocked). A deny-list blocks listed items (everything else is allowed).' },
  { match: ['canonical json'], def: 'JSON written in one exact standard form (sorted keys, no extra spaces), so the same data always produces the same bytes.' },
  { match: ['state machine', 'fsm', 'finite-state machine'], def: 'A model where something is always in exactly one named state, and only listed transitions between states are allowed.' },
  { match: ['tool', 'tools'], def: 'A function the agent can ask to run (search, calculate, look up a ticket), giving the LLM the ability to act and fetch facts.' },
  { match: ['dashboard'], def: 'A page showing live metrics so operators can see the system’s health at a glance.' },
  { match: ['throughput'], def: 'How much work gets done per unit of time, e.g. requests per second.' },
  { match: ['webhook', 'webhooks'], def: 'An HTTP request one system sends to another when something happens, like “deploy finished”.' },
];
