// Study notes for each lab's worked answer.
// `at` is a substring of the solution line the note explains (first match wins).
// scripts/verify-labs.mjs fails if a substring is missing, so notes cannot drift from the code.
export const NOTES = {
  'l01-perimeter': [
    { at: 'self._patterns = [re.compile', note: 'Compile the regexes once at construction. Re-compiling per request wastes CPU on every call.' },
    { at: 'if len(text) > self.max_len', note: 'Cheapest check first. It also protects the regex engine from giant inputs. `ValueError` maps to status `rejected`.' },
    { at: 'sanitised = html.escape(text)', note: 'Escape before matching, so the patterns see the same text that would reach logs, UIs and the model.' },
    { at: 'raise PermissionError("Potential prompt injection', note: 'Fail closed. Injection is an authorization failure, so it uses the same exception class as "unauthorized" and is counted as `blocked`.' },
    { at: 'bucket = (user_id, int(self.clock() // 60))', note: 'A per-user, per-minute bucket key. The injected clock makes this deterministic in tests.' },
  ],
  'l01-agent': [
    { at: 'clean = self.security.process(prompt, user_id)', note: 'L4 runs first, structurally. Nothing below this line can execute for an injected prompt.' },
    { at: 'tools = self.tools.available(permissions)', note: 'L3: only tools the caller may use ever reach the prompt (least privilege).' },
    { at: 'messages = history + [{"role": "user", "content": clean}]', note: 'L2 history + the sanitized user turn. Never the raw prompt.' },
    { at: 'text = self.tools.filter_output(resp["text"])', note: 'Egress filter: redact secrets on the way out, after the model answers.' },
    { at: 'self.metrics.record("blocked")', note: 'Record on the exception path, then re-raise. Security events are the highest-value dashboard series.' },
  ],
  'l02-orchestrator': [
    { at: 'SAFE_EXPR = re.compile', note: 'An allowlist of characters: digits, operators, parentheses, dot, space. No letters means no names, calls or dunder tricks.' },
    { at: 'def _done(self, outcome, result)', note: 'One helper records every outcome, so no return path can forget to update metrics.' },
    { at: 'if schema is None:', note: 'Unknown tool → fail closed. Model output naming a tool does not make it exist.' },
    { at: 'if schema.required_permission not in permissions:', note: 'Authorization before validation: a caller without permission learns nothing about the parameters.' },
    { at: 'except Exception as e:', note: 'Runtime errors become a structured `failed` result instead of crashing the request.' },
  ],
  'l03-window': [
    { at: 'while len(msgs) // 2 > self.max_turns:', note: 'Turn budget: drop the oldest user/assistant pair (2 messages) until the count fits.' },
    { at: 'while len(msgs) > 2 and self._tokens(msgs) > self.max_tokens:', note: 'Token budget: same trimming, but `len(msgs) > 2` guarantees the newest pair always survives.' },
    { at: 'return [dict(m) for m in self._sessions.get(session, [])]', note: 'Return copies, so callers cannot mutate stored history by accident.' },
  ],
  'l03-cache': [
    { at: 'return " ".join(q.lower().split())', note: 'Normalize: lowercase and collapse whitespace so trivially different queries share an entry.' },
    { at: 'self._data.popitem(last=False)', note: 'OrderedDict keeps insertion/recency order. `last=False` pops the least-recently-used entry.' },
    { at: 'if entry and (self.clock() - entry["ts"]) < self.ttl:', note: 'A hit must be both present and fresh. Strict `<` means an entry is expired exactly at `ttl`.' },
    { at: 'self._data.move_to_end(k)', note: 'Mark as most-recently-used on every hit and every set.' },
    { at: 'del self._data[k]', note: 'An expired entry is deleted and counted as an eviction and a miss.' },
  ],
  'l04-bucket': [
    { at: 'self.tokens = min(self.capacity, self.tokens + (now - self.last) * self.refill_rate)', note: 'Lazy refill: compute tokens earned since the last call, capped at capacity. No background timer needed.' },
    { at: 'if self.tokens >= n:', note: 'Spend only if enough tokens exist. A refused request does not consume anything.' },
    { at: 'if tier not in TIERS:', note: 'Unknown tiers fail loudly instead of silently getting a default limit.' },
    { at: 'self.buckets[user] = TokenBucket(cap, rate, self.clock)', note: 'One bucket per user, sized from tier config. New plans are a dict entry, not new code.' },
  ],
  'l04-cost': [
    { at: 'cost = input_tokens / 1000', note: 'Input and output tokens have different prices. Account for each separately, per request.' },
    { at: 'if before < threshold <= after:', note: 'Edge-triggered alert: fires only on the request that crosses the threshold, never again after.' },
    { at: 'return max(0.0, self.budget - self.spend.get(user, 0.0))', note: 'Remaining budget never goes negative, and unknown users start with the full budget.' },
  ],
  'l05-guard': [
    { at: 'self.compiled = [(name, re.compile(p)) for name, p in PATTERNS.items()]', note: 'Compile once, keep dict order: secrets first, so a key is not partly eaten by a broader pattern.' },
    { at: 'text, n = pattern.subn(f"[{name.upper()}]", text)', note: '`subn` redacts and counts in one pass. Each pattern runs on the already-redacted text.' },
    { at: 'blocked = any(c in SECRET_CATEGORIES for c in counts)', note: 'Secrets block the response; PII is only redacted. Different categories, different policy.' },
  ],
  'l05-hmac': [
    { at: 'return hmac.new(self.key, payload.encode(), hashlib.sha256).hexdigest()', note: 'Standard HMAC-SHA256 over the payload bytes, returned as hex.' },
    { at: 'return hmac.compare_digest(self.sign(payload), signature)', note: 'Constant-time comparison. `==` leaks how many leading characters matched.' },
    { at: 'return "unexpected_accept" if expect_reject else "hmac_ok"', note: 'Intent-aware status: a valid signature when you expected tampering is the real failure.' },
  ],
  'l06-red': [
    { at: 'rank = max(1, math.ceil((p / 100) * len(ordered)))', note: 'Nearest-rank: ceil of p% of n, never below rank 1. Deterministic and easy to test.' },
    { at: 'return "ERROR" if status >= 400 else "WARNING" if latency_ms >= 500 else "INFO"', note: 'Failure beats slowness: a slow 500 is ERROR, a slow 200 is WARNING.' },
    { at: '}, sort_keys=True)', note: 'Stable key order makes log lines diffable and testable. Note: no payload fields at all.' },
    { at: 'with self._lock:', note: 'One lock guards every counter, so a reader never sees a request counted without its latency.' },
    { at: 'lat = list(self.latencies)', note: 'Snapshot copies under the lock, then computes percentiles on the copy.' },
  ],
  'l07-sandbox': [
    { at: 'if name.split(".")[0] in BLOCKED:', note: 'Check the root module, so `os.path` is blocked along with `os`.' },
    { at: 'compiled = compile(code, "<sandbox>", "exec")', note: 'Compile before executing, so syntax errors are classified as ERROR, not TIMEOUT.' },
    { at: 'safe_builtins["__import__"] = self._guarded_import', note: 'Every `import` statement calls `__import__`. Replacing it in the sandbox builtins installs the guard.' },
    { at: 'if steps > self.max_steps:', note: 'Count line events and abort past the limit. This turns `while True` into a TIMEOUT outcome.' },
    { at: 'sys.settrace(old_trace)', note: 'Always restore the previous tracer in `finally`, even when the sandboxed code raises.' },
  ],
  'l08-supervisor': [
    { at: 'raise ValueError("empty batch")', note: 'Reject empty batches up front: speedup would divide by nothing.' },
    { at: 'self.workers.get(t["type"], self.workers["summarise"])', note: 'Route by type with a safe fallback for unknown types.' },
    { at: 'raw = await asyncio.gather(*coros, return_exceptions=True)', note: 'Fan out everything at once. `return_exceptions=True` turns failures into values instead of cancelling the batch.' },
    { at: 'if isinstance(r, Exception):', note: 'Failed tasks become `{ok: False}` records in their original position.' },
    { at: '"speedup": serial_ms / max(parallel_ms, 1e-6)', note: 'Speedup is measured: total task time over wall time. Guard against division by zero.' },
  ],
  'l09-calc': [
    { at: 'if isinstance(node, ast.Expression):', note: 'The parse root for `mode="eval"`. Recurse into its body.' },
    { at: 'not isinstance(node.value, bool)', note: 'Only int/float constants. `True` is an int in Python, so bools are rejected explicitly.' },
    { at: 'if isinstance(node.op, ast.Pow) and abs(right) > 100:', note: 'Guard exponents. `9 ** 9 ** 9` is valid arithmetic and a CPU bomb.' },
    { at: 'raise ValueError(f"unsupported: {type(node).__name__}")', note: 'Everything else (names, calls, attributes, strings) is rejected. Default deny.' },
  ],
  'l09-loop': [
    { at: 'm = ACTION_RE.search(thought)', note: 'Strict format: `Action: name[arg]`. Anything malformed returns None and is never executed.' },
    { at: 'for _ in range(self.max_steps):', note: 'The loop is bounded. A confused planner cannot run forever.' },
    { at: 'if "Final Answer:" in thought:', note: 'Stopping criterion #1: the planner says it is done.' },
    { at: 'if action and action[0] in TOOLS:', note: 'Only registered tools run. Unknown actions become an error observation.' },
    { at: 'return {"answer": None, "steps": history, "stopped_reason": "max_steps"}', note: 'Stopping criterion #2: budget exhausted. The full trace is still returned for debugging.' },
  ],
  'l10-template': [
    { at: 'text = text.replace("{{" + key + "}}", str(value))', note: 'Plain string replacement keeps the engine tiny and predictable.' },
    { at: 'missing = re.findall(r"\\{\\{(\\w+)\\}\\}", text)', note: 'Any placeholder left after rendering means a missing variable.' },
    { at: 'raise ValueError(f"unresolved template variables: {missing}")', note: 'Fail at render time, before a broken prompt reaches the model.' },
    { at: 'for category, keywords in CLASSIFICATION_RULES:', note: 'Rules are ordered: the first match wins, so put the most critical category first.' },
  ],
  'l11-parse': [
    { at: 'if not isinstance(obj, dict):', note: 'Syntax is not enough: the top level must be an object.' },
    { at: 'if t not in ALLOWED_ENTITY_TYPES:', note: 'Semantic validation: well-formed JSON with an unknown type still fails.' },
    { at: 'if isinstance(c, bool) or not isinstance(c, (int, float)):', note: 'Check bool first, because bool is a subclass of int.' },
    { at: 'max(0.0, min(1.0, float(c)))', note: 'Recoverable fields are clamped instead of rejected.' },
    { at: 'return ParseResult(False, error=str(e)[:240])', note: 'Never raise from the parser; truncate errors so raw payloads (and PII) do not leak into logs.' },
  ],
  'l12-fsm': [
    { at: 'if new_state not in TRANSITIONS.get(self.state, []):', note: 'The transition table is the policy. Anything not listed is illegal.' },
    { at: 'self.metrics["invalid_blocked"] += 1', note: 'Count the blocked attempt, then raise before touching any state.' },
    { at: 'from_state = self.state', note: 'Capture the source state before mutating, for the audit entry and recovery check.' },
    { at: 'if from_state is S.ERROR and new_state is S.IDLE:', note: 'Leaving ERROR for IDLE is a recovery, tracked separately from errors.' },
  ],
  'l13-runners': [
    { at: 'self.peak = max(self.peak, self.in_flight)', note: 'Track concurrency inside the tracked call, so the metric reflects real overlap.' },
    { at: 'self.in_flight -= 1', note: 'Decrement in `finally`, so failures do not leak in-flight counts.' },
    { at: 'results.append(await self._tracked(name, delay, payload))', note: 'Sequential baseline: one await at a time. Wall time ≈ sum of delays.' },
    { at: 'async with sem:', note: 'The semaphore caps how many calls are in flight at once.' },
    { at: 'results = await asyncio.gather(*[bounded(*t) for t in tasks], return_exceptions=True)', note: 'Bounded fan-out. Wall time ≈ slowest tool when the limit is high enough.' },
  ],
  'l14-window': [
    { at: 'if reserved >= max_tokens:', note: 'No headroom for the response is a configuration error, caught at construction.' },
    { at: 'i = min(range(len(self.messages)), key=lambda k: (self.messages[k]["priority"], k))', note: 'Lowest priority first; the index breaks ties so the oldest goes first.' },
    { at: 'dropped = others[:-keep] if keep else others[:]', note: 'Sliding window: keep only the newest `keep` non-system messages.' },
    { at: 'dropped.append(kept.pop(0))', note: 'Then enforce the token ceiling from the oldest side of what is left.' },
    { at: 'raise ValueError("cannot fit context within budget")', note: 'Never return an over-budget success.' },
  ],
  'l15-scorers': [
    { at: 'return " ".join(s.lower().strip().split()).rstrip(".!?")', note: 'Normalization decides what "the same answer" means. Keep it simple and shared by all metrics.' },
    { at: 'overlap = sum((Counter(a) & Counter(e)).values())', note: '`Counter & Counter` keeps the minimum count per token: overlap with multiplicity.' },
    { at: 'return 2 * precision * recall / (precision + recall)', note: 'Harmonic mean: high only when both precision and recall are high.' },
    { at: 'if normalize(case["actual"]).startswith(REFUSALS):', note: 'Check refusals first, so "Sorry, it is 1969" is not credited as containing the answer.' },
    { at: '"pass_rate": passed / n if n else 0.0', note: 'Guard empty suites instead of dividing by zero.' },
  ],
  'l16-tfidf': [
    { at: 'if len(w) > 3 and w.endswith("s"):', note: 'Light plural stemming: "vectors" → "vector", but short words like "bus" stay intact.' },
    { at: 'return {w: tf[w] * math.log((n + 1) / (df.get(w, 0) + 1) + 1) for w in tf}', note: 'TF × smoothed IDF. Words in every document get a low weight.' },
    { at: 'return dot / (na * nb) if na and nb else 0.0', note: 'Cosine: direction, not length. No shared terms → 0.0.' },
    { at: 'self._vecs = None', note: 'Writes invalidate the index; the next search rebuilds it lazily.' },
    { at: 'if results and results[0]["score"] >= self.hit_threshold:', note: 'A hit means the top result is actually relevant, not just present.' },
  ],
  'l17-dataset': [
    { at: 'if roles[0] != "system":', note: 'Trainers expect system first…' },
    { at: 'if roles[-1] != "assistant":', note: '…and assistant last, so the loss is computed on the reply.' },
    { at: 'random.Random(seed).shuffle(items)', note: 'A local, seeded generator: the same split on every machine, unaffected by other code.' },
    { at: 'valid = [e for e in examples if not validate_example(e)]', note: 'Only valid rows enter either split. Broken rows never contaminate validation.' },
  ],
  'l18-optimiser': [
    { at: 'best = max(candidates, key=lambda c: scores[c.id])', note: '`max` returns the first maximum, so ties go to the earlier candidate.' },
    { at: 'deployed = improvement >= self.min_pp', note: 'The gate: a winner must beat the baseline by at least `min_pp` points.' },
    { at: 'winner, winner_rate = (best, scores[best.id]) if deployed else (baseline, base_rate)', note: 'Below the gate, the baseline stays in production.' },
    { at: 'archived=[c.id for c in candidates if c.id != winner.id]', note: 'Every loser is archived as evidence, never deleted.' },
  ],
  'l19-debate': [
    { at: 'if any(k in q for k in CREATIVE):', note: 'Creative intent wins over keywords: a poem about medication does not need debate.' },
    { at: 'critiques = await asyncio.gather(*[self.critic(i, draft) for i in range(self.n_critics)])', note: 'Critics are independent, so they run in parallel: latency ≈ one critic hop.' },
    { at: 'calls = 1 + self.n_critics + 1', note: 'Generator + N critics + arbiter. Report this next to the accuracy gain.' },
  ],
  'l20-graph': [
    { at: 'if not 0 <= cost <= 100:', note: 'Validate before writing: graph data is audit evidence.' },
    { at: 'row = chain.setdefault(e["tool"]', note: 'Aggregate per tool: call count, total cost and the set of agents involved.' },
    { at: 'rows.sort(key=lambda r: (-r["total_cost"], r["tool"]))', note: 'Top spenders first; the tool name breaks ties deterministically.' },
    { at: 'return rows[:limit]', note: 'Every query is bounded, like `LIMIT 100` in Cypher.' },
  ],
  'l21-pipeline': [
    { at: 'return PHONE.sub("[PHONE]", EMAIL.sub("[EMAIL]", text))', note: 'Redact at ingestion, before traces become eval cases or get stored.' },
    { at: 'if q and q not in seen:', note: 'Skip blanks and duplicates while preserving first-seen order.' },
    { at: 'deployed = improvement > IMPROVEMENT_THRESHOLD_PP', note: 'Strictly greater: exactly +3.0pp holds. The gate is a named constant you can grep.' },
    { at: 'self.metrics["deployments" if deployed else "no_change"] += 1', note: 'Hold decisions are recorded too: "no change" is evidence.' },
  ],
  'l22-manifests': [
    { at: 'and strategy.get("rollingUpdate", {}).get("maxUnavailable") == 0', note: 'Zero-downtime: old pods stay until new ones pass readiness.' },
    { at: 'return all(all(k in res.get(kind, {}) for k in ("cpu", "memory")) for kind in ("requests", "limits"))', note: 'Both requests and limits, each with cpu and memory. `.get(…, {})` makes missing sections fail instead of crash.' },
    { at: '"secrets_not_in_configmap": not any(SECRET_KEY.search(k) for k in configmap.get("data", {}))', note: 'Key names that look like credentials do not belong in a ConfigMap.' },
    { at: '"non_root": bool(users) and users[-1] not in ("root", "0")', note: 'The last USER line wins in a Dockerfile, so check that one.' },
  ],
  'l23-keda': [
    { at: 'needed = min(math.ceil(depth / self.threshold), self.max_replicas) if depth > 0 else 0', note: 'One replica per `threshold` queued requests, capped, and zero when the queue is empty.' },
    { at: 'needed = max(needed, self.cron_floor)', note: 'Business-hours floor avoids cold starts for the first morning requests.' },
    { at: 'return round(100 * (1 - sum(reps) / always_on), 1)', note: 'Savings = replica-hours used vs running peak capacity all day.' },
  ],
  'l24-chain': [
    { at: 'return json.dumps(d, sort_keys=True, separators=(",", ":"))', note: 'Canonical bytes: key order and whitespace can never change the hash.' },
    { at: 'body = {k: v for k, v in entry.items() if k != "entry_hash"}', note: 'Hash everything except the hash itself, including `prev_hash` and `seq`.' },
    { at: 'prev = chain[-1]["entry_hash"] if chain else GENESIS', note: 'Each entry points at the previous hash; the first points at GENESIS.' },
    { at: 'if e.get("prev_hash") != expected_prev or e.get("seq") != i or e.get("entry_hash") != _hash(e):', note: 'Check the link, the position and the content. Pointers alone miss field edits.' },
  ],
  'l25-phi': [
    { at: 'return sorted(name for name, rx in cls.COMPILED.items() if rx.search(text))', note: 'Return PHI types only, sorted for stable audit entries.' },
    { at: 'text = rx.sub(f"[{name}]", text)', note: 'Typed labels keep structure without keeping the identifier.' },
    { at: 'if s is None:', note: 'Unknown sessions are treated exactly like expired ones.' },
    { at: 'if self.clock() - s["last"] >= SESSION_TIMEOUT_SECS:', note: 'Uses the module constant, never a constructor argument: there is no knob to bypass.' },
    { at: 'self.sessions.pop(sid, None)', note: 'Expired sessions are removed, so a later touch cannot revive them without re-authenticating.' },
  ],
  'l26-failover': [
    { at: 'return cfg["request_interval_secs"] * cfg["failure_threshold"]', note: 'Detection time is explicit: interval × consecutive failures.' },
    { at: 'promoted = bool(t.health.get(t.standby))', note: 'Only promote a standby that is actually healthy.' },
    { at: 'rto = detection_secs(self.cfg) + warmup_secs', note: 'RTO = time to notice + time to serve from DR.' },
    { at: '"rpo_met": replica_lag_secs <= TARGET_RPO_SECS,', note: 'RPO is independent of RTO: a fast flip with big replica lag still fails.' },
    { at: '"status": "VALIDATED" if passed == len(checks) else "FAILED"', note: 'Fail closed: any single miss fails the DR test.' },
  ],
};
